# Settings

Version: 3.0.0

Language: EN

MultiWorld:
  EnableResourcePack: true
  ResourcePackURL: https://www.dropbox.com/s/3jgd7fpn8nxgzrh/testtest.zip?dl=1
  NotifyMessage: true

LocalChatDist: -1

NoPos: true

Survival:
  Enabled: true
  
  BreakOnlyWith:
    Axe: true
    Pickaxe: true
    Shovel: true
    Shears: true
    Sickle: true
    
  PlaceOnlyWith:
    Hammer: true

  DropRate:
    Flint: 0.5
    Stick: 0.25

  Torch: true

Mechanics:
  SharedWorkbench: true
  
  BedFatigueLevel: true
  
  SlowArmor: true
  ReinforcedLeatherArmor: true
  Bow: true
  RecurveBow: true
  GrapplingHook: true
  MedicalKit: true
  ReducedIronNugget: true
  ReducedGoldNugget: true
  
  StatusScoreboard: true
  AlertInterval: 20
  RawMeatHunger: true
  EmptyPotions: true
  PoisonousPotato: true
  CookieHealthBoost: true
  BeetrootStrength: true
  FoodDiversity: true
  Thirst:
    Enabled: true
    PurifyWater: true
    MeltSnow: true
    DrainRate: 1.0
  
  CompassWaypoint: true
  Clownfish: true
  
  FermentedSkin: true
  
  LivingSlime: true
  
  SnowballRevamp: true
  SnowGenerationRevamp: false
  
  FishingRod: true
  
  FarmingProducts:
    Bread: true
    Cookie: true
  
  Chairs:
    Enabled: true
    MaxChairWidth: 2
    AllowedBlocks:
      - OAK_STAIRS
      - SPRUCE_STAIRS
      - JUNGLE_STAIRS
      - BIRCH_STAIRS
      - ACACIA_STAIRS
      - DARK_OAK_STAIRS
      - SANDSTONE_STAIRS
      - COBBLESTONE_STAIRS
      - BRICK_STAIRS
      - STONE_BRICK_STAIRS
      - NETHER_BRICK_STAIRS
      - QUARTZ_STAIRS
      - RED_SANDSTONE_STAIRS
      - PURPUR_STAIRS
      - PRISMARINE_STAIRS
      - PRISMARINE_BRICK_STAIRS
      - DARK_PRISMARINE_STAIRS

Recipes:
  Saddle: true
  Nametag: true
  PackedIce: true
  LeatherBard: true
  IronBard: true
  GoldBard: true
  DiamondBard: true
  ClayBrick: true
  QuartzBlock: true
  WoolString: true
  WebString: true
  Ice: true
  Clay: true
  Diorite: false
  Granite: false
  Andesite: false
  Gravel: true
  Slimeball: true
  Cobweb: true
  SaplingToSticks: true

LegendaryItems:
  CanRepair: true
  ValkyrieAxe: true
  QuartzPickaxe: true
  ObsidianMace: true
  GiantBlade: true
  BlazeSword: true
  NotchApple: true
  GoldArmorBuff: true